import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Check, Clock3, Edit3, Play, RotateCcw } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { ExecutionBadge, Metric, PageHeader, Section, StatusBadge } from "@/components/ops-ui";
import { Button } from "@/components/ui/button";
import { targets } from "@/lib/mock-data";
export const Route=createFileRoute("/monitoring/$targetId")({ head:()=>({meta:[{title:"Target events — Northstar Ops"},{name:"description",content:"Inspect target observations, recovery history, and configuration."},{property:"og:title",content:"Target events — Northstar Ops"},{property:"og:description",content:"Inspect target observations, recovery history, and configuration."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:DetailPage });
const events=[{time:"10:42:12",title:"Check passed",text:"HTTP 200 in 184 ms",tone:"healthy" as const,place:"This PC"},{time:"10:41:12",title:"Recovered",text:"Response returned to expected range after 2 failed attempts",tone:"healthy" as const,place:"Oracle"},{time:"10:39:12",title:"Threshold breached",text:"HTTP 504 · upstream request timed out after 10 s",tone:"error" as const,place:"Oracle"},{time:"10:38:12",title:"Response slowed",text:"Latency rose to 2.8 s",tone:"degraded" as const,place:"This PC"}];
function DetailPage(){const {targetId}=Route.useParams(); const target=targets.find(t=>t.id===targetId); if (!target) return <AppShell><div className="py-20 text-center"><p className="font-semibold">Target not found</p><Button asChild className="mt-4"><Link to="/">Back to monitoring</Link></Button></div></AppShell>; return <AppShell><div className="space-y-5"><Link to="/" className="inline-flex items-center gap-1 text-xs font-medium text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3"/>Monitoring</Link><PageHeader eyebrow="Target detail" title={target.name} description="Current state, recent observations, and recovery context." actions={<div className="flex gap-2"><Button variant="outline" size="sm"><Edit3/>Edit</Button><Button size="sm"><Play/>Run now</Button></div>}/>
 <div className="grid gap-4 border-b pb-5 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Current status" value={target.status[0].toUpperCase()+target.status.slice(1)} detail="Recovered 1 min ago"/><Metric label="Success rate" value="98.7%" detail="Last 24 hours"/><Metric label="Median latency" value="184 ms" detail="p95 420 ms"/><Metric label="Next check" value={target.next} detail="60 sec interval"/></div>
 <div className="grid gap-5 lg:grid-cols-[minmax(0,1.4fr)_minmax(280px,.6fr)]"><div className="space-y-5"><div className="rounded-md border border-warning/30 bg-warning-soft p-4"><div className="flex items-start gap-3"><RotateCcw className="mt-0.5 size-4 shrink-0 text-warning"/><div><p className="text-sm font-semibold text-warning">Recovered after a brief outage</p><p className="mt-1 text-xs text-muted-foreground">Oracle observed two timeouts between 10:38 and 10:41. Local remained healthy. Both sources now report HTTP 200.</p></div></div></div><Section title="Event history" description="Newest observations first"><div className="relative ml-2 border-l">{events.map((e,i)=><div key={e.time} className="relative pb-5 pl-6 last:pb-0"><span className={`absolute -left-[5px] top-1 size-2.5 rounded-full border-2 border-background ${e.tone==="healthy"?"bg-success":e.tone==="error"?"bg-destructive":"bg-warning"}`}/><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-3"><div><p className="text-sm font-semibold">{e.title}</p><p className="mt-0.5 text-xs text-muted-foreground">{e.text}</p><div className="mt-2"><ExecutionBadge value={e.place as "Local"|"Oracle"}/></div></div><time className="font-mono text-xs text-muted-foreground">{e.time}</time></div></div>)}</div></Section></div>
 <aside className="space-y-5"><Section title="Identity"><dl className="grid grid-cols-2 gap-x-4 gap-y-3 text-xs"><dt className="text-muted-foreground">Status</dt><dd><StatusBadge status={target.status}/></dd><dt className="text-muted-foreground">Execution</dt><dd><ExecutionBadge value={target.execution}/></dd><dt className="text-muted-foreground">Device</dt><dd className="font-medium">{target.device}</dd><dt className="text-muted-foreground">Target ID</dt><dd className="font-mono">mon_7f29b</dd></dl></Section><Section title="Configuration summary"><dl className="space-y-3 text-xs"><div><dt className="text-muted-foreground">URL</dt><dd className="mt-1 break-all font-mono">https://api.example.test/health</dd></div><div className="grid grid-cols-2 gap-3"><div><dt className="text-muted-foreground">Method</dt><dd className="mt-1 font-semibold">GET</dd></div><div><dt className="text-muted-foreground">Timeout</dt><dd className="mt-1 font-semibold">10 sec</dd></div></div><div><dt className="text-muted-foreground">Expected</dt><dd className="mt-1 flex items-center gap-1.5"><Check className="size-3 text-success"/>HTTP 200–299</dd></div></dl></Section><div className="flex items-center gap-2 rounded-md border p-3 text-xs text-muted-foreground"><Clock3 className="size-4"/>Updated by Maya Chen 2 days ago</div></aside></div>
 </div></AppShell>}
